openapi: '3.0.2'
info:
  title: Contact book
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      responses:
        '200':
          description: OK
